# shortcode = "PTC-W001"
title = "Potential hardcoded credential detected"
category = "security"
description = """
Potential hardcoded credential. Sensitive information like password shouldn't be hardcoded. Use an environment variable instead.
"""
