query integrationsWithDetails(
  $level: IntegrationSettingsLevel
  $ownerId: ID
  $repositoryId: ID
  $onlyInstalled: Boolean
) {
  integrations(
    level: $level
    ownerId: $ownerId
    repositoryId: $repositoryId
    onlyInstalled: $onlyInstalled
  ) {
    shortcode
    name
    logo
    installedOn
    settings
    options
  }
}
