query integrationInstallationStatus(
  $shortcode: String!
  $level: IntegrationSettingsLevel
  $ownerId: ID
  $repositoryId: ID
) {
  integration(
    shortcode: $shortcode
    level: $level
    ownerId: $ownerId
    repositoryId: $repositoryId
  ) {
    installed
  }
}
