query($q: String) {
  analyzers(q: $q) {
    edges {
      node {
        shortcode
        name
        owner
        descriptionRendered
        issuesCount
        autofixableIssuesCount
        updatedOn
        version
        category
        analyzerLogo
        publishedOn
      }
    }
  }
}
