query RepoList($login: String!, $provider: VCSProviderChoices!, $after: String!, $limit: Int!) {
  owner(login: $login, provider: $provider) {
    id
    repositories(first: $limit, after: $after) {
      totalCount
      pageInfo {
        hasNextPage
      }
      edges {
        node {
          id
          name
          vcsProvider
          ownerLogin
          isActivated
          isFork
          isPrivate
          isStarred
        }
      }
    }
  }
}
