query repositoryIssueList(
  $provider: VCSProviderChoices!
  $owner: String!
  $name: String!
  $limit: Int
  $after: String
  $issueType: String
  $product: String
  $analyzer: String
  $sort: String
  $q: String
  $autofixAvailable: Boolean
  $auditRequired: Boolean
  $recommended: Boolean
  $all: Boolean
) {
  repository(provider: $provider, owner: $owner, name: $name) {
    id
    issues(
      all: $all
      first: $limit
      after: $after
      issueType: $issueType
      product: $product
      analyzer: $analyzer
      sort: $sort
      q: $q
      autofixAvailable: $autofixAvailable
      auditRequired: $auditRequired
      recommended: $recommended
    ) {
      totalCount
      edges {
        node {
          id
          issueType
          title
          shortcode
          description
          occurrenceCount
          createdAt
          analyzerName
          analyzerLogo
          seenIn
          firstSeen
          lastSeen
          modifiedAt
          trend {
            trendHint
            trendValue
            trendDirection
            trendPositive
          }
          autofixAvailable
          raisedInFiles
          severity
        }
      }
    }
  }
}
