query(
  $provider: VCSProviderChoices!
  $owner: String!
  $name: String!
  $limit: Int
  $after: String
  $issueType: String
  $analyzer: String
  $sort: String
  $q: String
  $autofixAvailable: Boolean
  $all: Boolean
) {
  repository(provider: $provider, owner: $owner, name: $name) {
    id
    issues(
      all: $all
      first: $limit
      after: $after
      issueType: $issueType
      analyzer: $analyzer
      sort: $sort
      q: $q
      autofixAvailable: $autofixAvailable
    ) {
      totalCount
      edges {
        node {
          id
          issueType
          title
          shortcode
          description
          occurrenceCount
          createdAt
          analyzerName
          analyzerLogo
          seenIn
          firstSeen
          lastSeen
          modifiedAt
          pastValue
          autofixAvailable
          raisedInFiles
        }
      }
    }
  }
}
