query singleRepoIssue($shortcode: String!) {
  issue(shortcode: $shortcode) {
    shortcode
    title
    issueType
    descriptionRendered
    analyzer {
      id
      shortcode
      name
    }
    issueType
    shortcode
    title
  }
}
