query viewer {
  viewer {
    id
    connectedVcsProviders
    fullName
    firstName
    lastName
    email
    avatar
    lastLogin
    isActive
    isAsgardian
    isBetaTester
    isStaff
    dashboardContext
    availableCredits
    missiveUserHash
    dateJoined
    primaryOwner {
      id
      login
      vcsProvider
      billingEmail
    }
  }
}
