query {
  viewer {
    id
    fullName
    firstName
    lastName
    email
    avatar
    lastLogin
    isActive
    isAsgardian
    isStaff
    dashboardContext
    availableCredits
    missiveUserHash
    primaryOwner {
      id
      login
      vcsProvider
      billingEmail
    }
  }
}
