query {
  viewer {
    id
    recommendedIssues(first: 5) {
      edges {
        node {
          id
          title
          shortcode
          issueType
          modifiedAt
          createdAt
          seenIn
          firstSeen
          lastSeen
          occurrenceCount
          autofixAvailable
          raisedInFiles
          repositoryInstance {
            id
            name
            vcsProvider
            owner {
              id
              login
            }
          }
        }
      }
    }
  }
}
