version = 1
exclude_patterns = []
test_patterns = []

[[analyzers]]
  name = "php"
  enabled = true

[[analyzers]]
  name = "python"
  enabled = true

[[analyzers]]
  name = "javascript"
  enabled = true

[[transformers]]
  name = "google-java-format"
  enabled = true

[[transformers]]
  name = "yapf"
  enabled = true

[[transformers]]
  name = "autopep8"
  enabled = true

[[transformers]]
  name = "standardjs"
  enabled = true
