version: 2

jobs:
  build:
    docker:
      # Golang image - primary
      - image: golang:1.12.9-alpine3.10

    working_directory: ~/repo

    steps:
      - run:
          name: Install necessities
          command: |
            echo "https://mirror.csclub.uwaterloo.ca/alpine/v3.10/main" >/etc/apk/repositories
            echo "https://mirror.csclub.uwaterloo.ca/alpine/v3.10/community" >>/etc/apk/repositories
            apk update
            apk add bash curl git openssh
            mkdir /code -p

      - checkout

      - run:
          name: Configure git to use ssh
          command: |
            git config --global url.git@github.com:.insteadOf https://github.com/

      - run:
          name: Build cli
          command: |
            GOOS=linux GOARCH=amd64 go build -tags static_all -o /tmp/deepsource .
            chmod +x /tmp/deepsource

      - run:
          name: Clone the test repository
          command: |
            git clone https://github.com/deepsourcelabs/july.git /code

      - run:
          name: Run report value argument tests
          command: CGO_ENABLED=0 go test -v ./tests/... -run TestReportKeyValueWorkflow
          no_output_timeout: 60s

      - run:
          name: Run report value file argument tests
          command: CGO_ENABLED=0 go test -v ./tests/... -run TestReportKeyValueFileWorkflow
          no_output_timeout: 60s

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
