query fetchRepositoryMetricsCaptured(
  $provider: VCSProviderChoices!
  $owner: String!
  $name: String!
  $metricType: MetricTypeChoices
  $fetchPerms: Boolean!
) {
  repository(provider: $provider, owner: $owner, name: $name) {
    id
    metricsCaptured(metricType: $metricType) {
      id
      shortcode
      name
      category
    }
    userPermissionMeta @include(if: $fetchPerms)
  }
}
