query repositoryToActivateList(
  $login: String!
  $provider: VCSProviderChoices!
  $isActivated: Boolean
  $limit: Int
  $offset: Int
  $query: String
  $kindIn: [RepositoryKindChoices]!
) {
  owner(login: $login, provider: $provider) {
    id
    repositories(
      isActivated: $isActivated
      first: $limit
      offset: $offset
      name_Icontains: $query
      kindIn: $kindIn
    ) {
      totalCount
      edges {
        node {
          id
          createdAt
          displayName
          name
          vcsProvider
          ownerLogin
          isPrivate
          isStarred
          latestCommitOid
          defaultBranchName
          lastAnalyzedAt
          isActivated
          kind
          supportedAnalyzers
          subRepos {
            totalCount
          }
        }
      }
    }
  }
}
