query($name: String!, $owner: String!, $provider: VCSProviderChoices!, $q: String!) {
  repository(name: $name, owner: $owner, provider: $provider) {
    id
    addableMembers(q: $q) {
      totalCount
      edges {
        node {
          id
          role
          isPrimaryUser
          user {
            id
            firstName
            lastName
            fullName
            email
            avatar
            dateJoined
          }
        }
      }
    }
  }
}
