query($provider: VCSProviderChoices!, $owner: String!, $name: String!, $lastDays: Int!) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    name
    autofixedIssueTrend(lastDays: $lastDays)
  }
}
