query RepoAutofixStats($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    autofixableIssuesMetadata {
      autofixableIssueCount
      estimatedTimeSaved
    }
    autofixableIssuesPerAnalyzer {
      analyzer {
        shortcode
        logo
        analyzerLogo
        name
      }
      filesAffected
      issueCount
    }
  }
}
