query($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    name
    supportedAnalyzers
    availableAnalyzers {
      edges {
        node {
          id
          shortcode
          name
          logo
          analyzerLogo
        }
      }
    }
  }
}
