query BaseRepoQuery($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    vcsUrl
    isActivated
    isPrivate
    isStarred
    kind
    errorCode
    renderedErrorMessage
    fullName
    displayName
    defaultBranchName
    vcsProvider
    vcsDefaultBranchUrl
    errorMessage
    canBeActivated
    isAutofixEnabled
    blobUrlRoot
    path
    lastRun {
      id
      runId
      config
      commitOid
      branchRunCount
      status
      finishedAt
    }
    latestAnalysisRun {
      id
      runId
      config
      commitOid
      branchRunCount
      status
      finishedAt
    }
    owner {
      id
    }
  }
}
