query BaseRepoQuery($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    isActivated
    isPrivate
    isStarred
    errorCode
    renderedErrorMessage
    fullName
    defaultBranchName
    vcsProvider
    vcsDefaultBranchUrl
    errorMessage
    canBeActivated
    isAutofixEnabled
    blobUrlRoot
    lastRun {
      id
      runId
      config
      commitOid
      branchRunCount
      status
      finishedAt
    }
    latestAnalysisRun {
      id
      runId
      config
      commitOid
      branchRunCount
      status
      finishedAt
    }
  }
}
