query RepoDetails($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    name
    isPrivate
    isStarred
    kind
    canBeActivated
    fullName
    errorCode
    renderedErrorMessage
    userPermissionMeta
    hasTestCoverage
    latestAnalysisRun {
      id
      runId
      config
      commitOid
      branchRunCount
      status
      finishedAt
    }
    isActivated
    blobUrlRoot
    defaultBranchName
    widgetsAvailable
    allWidgets
    vcsDefaultBranchUrl
    hasViewerEditAccess
    vcsUrl
    vcsHost
    vcsProvider
    config
    supportedAnalyzers
    isAutofixEnabled
    autofixGithubAppInstallationUrl
    autofixBitbucketAddonInstallationUrl
    availableAnalyzers {
      edges {
        node {
          id
          shortcode
          name
          logo
          analyzerLogo
        }
      }
    }
  }
}
