query RepoDetails($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    name
    isPrivate
    isStarred
    canBeActivated
    userPermissionMeta
    latestAnalysisRun {
      id
      runId
      config
      commitOid
      branchRunCount
      status
      finishedAt
    }
    isActivated
    blobUrlRoot
    defaultBranchName
    vcsDefaultBranchUrl
    hasViewerEditAccess
    vcsUrl
    vcsHost
    vcsProvider
    config
    supportedAnalyzers
    isCommitPossible
    isAutofixEnabled
    autofixGithubAppInstallationUrl
    autofixBitbucketAddonInstallationUrl
    availableAnalyzers {
      edges {
        node {
          id
          shortcode
          name
          logo
          analyzerLogo
        }
      }
    }
    autofixableIssuesMetadata {
      autofixableIssueCount
      estimatedTimeSaved
    }
    autofixableIssuesPerAnalyzer {
      analyzer {
        shortcode
        logo
        analyzerLogo
        name
      }
      filesAffected
      issueCount
    }
  }
}
