query ($repositoryId: ID!, $shortcode: String!) {
  repository: node(id: $repositoryId) {
    ... on Repository {
      issue(shortcode: $shortcode) {
        id
        raisedInFiles
      }
    }
  }
}
