query issueOccurrenceDistributionByIssueType(
  $provider: VCSProviderChoices!
  $owner: String!
  $name: String!
  $analyzer: String
  $q: String
  $autofixAvailable: Boolean
) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    issueOccurrenceDistributionByIssueType(
      analyzer: $analyzer
      q: $q
      autofixAvailable: $autofixAvailable
    ) {
      key
      count
    }
  }
}
