query repositoryIssueTrend(
  $provider: VCSProviderChoices!
  $owner: String!
  $name: String!
  $lastDays: Int!
) {
  repository(provider: $provider, name: $name, owner: $owner) {
    id
    issueTrend(lastDays: $lastDays)
    resolvedIssueTrend(lastDays: $lastDays)
  }
}
