query repositoryList(
  $login: String!
  $provider: VCSProviderChoices!
  $isActivated: Boolean
  $limit: Int
  $after: String
  $query: String
) {
  owner(login: $login, provider: $provider) {
    id
    repositories(isActivated: $isActivated, first: $limit, after: $after, name_Icontains: $query) {
      totalCount
      edges {
        node {
          id
          displayName
          name
          vcsProvider
          ownerLogin
          modifiedAt
          isActivated
          isFork
          isPrivate
          isStarred
          latestCommitOid
          defaultBranchName
          lastAnalyzedAt
          kind
          availableAnalyzers {
            edges {
              node {
                id
                name
                shortcode
                analyzerLogo
              }
            }
          }
          primaryAnalyzer {
            id
            name
            shortcode
            analyzerLogo
          }
          canBeActivated
          supportedAnalyzers
        }
      }
    }
  }
}
