query metricsData(
  $provider: VCSProviderChoices!
  $owner: String!
  $name: String!
  $lastDays: Int!
) {
  repository(provider: $provider, owner: $owner, name: $name) {
    id
    uniqueNamespaceKeys
    metricsData(lastDays: $lastDays)
  }
}
