query recentlyActiveRepoList(
  $login: String!
  $provider: VCSProviderChoices!
  $limit: Int
  $after: String
  $fetchAnalyzers: Boolean!
) {
  owner(login: $login, provider: $provider) {
    id
    repositories(isActivated: true, first: $limit, after: $after) {
      totalCount
      edges {
        node {
          id
          displayName
          name
          vcsProvider
          ownerLogin
          isActivated
          isFork
          isPrivate
          lastAnalyzedAt
          kind
          availableAnalyzers @include(if: $fetchAnalyzers) {
            edges {
              node {
                id
                name
                shortcode
                analyzerLogo
              }
            }
          }
        }
      }
    }
  }
}
