query RepositoryWidgets($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, owner: $owner, name: $name) {
    id
    widgets
    widgetsDisplay
    widgetsAvailable
    allWidgets
  }
}
