query analyzerDistribution($reportKey: String!, $level: ReportLevel!, $objectId: ID!) {
  issueDistributionByAnalyzer(reportKey: $reportKey, level: $level, objectId: $objectId) {
    slug
    name
    value
    logoUrl
  }
}
