query categoryDistribution($reportKey: String!, $level: ReportLevel!, $objectId: ID!) {
  issueDistributionByCategory(reportKey: $reportKey, level: $level, objectId: $objectId) {
    slug
    name
    value
  }
}
