query codeCoverageReport(
  $login: String!
  $provider: VCSProviderChoices!
  $first: Int
  $offset: Int
  $sort: String
  $q: String
  $before: String
  $after: String
  $last: Int
) {
  owner(login: $login, provider: $provider) {
    id
    repositoriesCoverageReport(
      first: $first
      offset: $offset
      sort: $sort
      q: $q
      before: $before
      after: $after
      last: $last
    ) {
      totalCount
      edges {
        node {
          id
          name
          lcvValue
          lcvIsPassing
          bcvValue
          bcvIsPassing
        }
      }
    }
  }
}
