query publicReportBase($reportId: String!, $token: String) {
  publicReport(reportId: $reportId, token: $token) {
    id
    reportId
    label
    createdAt
    views
    isRestricted
    reportKeys
    source
    level
    shareHistoricalData
    owner {
      id
      login
      avatar
    }
    repository {
      id
      name
      isPrivate
    }
  }
}
