query publicReportComplianceIssues(
  $reportId: String!
  $token: String
  $reportKey: String!
  $isOwasp: Boolean!
) {
  publicReport(reportId: $reportId, token: $token) {
    id
    complianceIssues(key: $reportKey) {
      issueId
      title
      occurrence {
        high
        medium
        low
        total
      }
      rank
    }

    complianceIssuesSeverityMap(key: $reportKey) @include(if: $isOwasp) {
      high
      medium
      low
      total
    }
  }
}
