query publicReportCategoryDistribution($key: String!, $reportId: String!, $token: String) {
  publicReport(reportId: $reportId, token: $token) {
    id
    issueDistributionByCategory(key: $key) {
      slug
      name
      value
      logoUrl
    }
  }
}
