query repoListForReports(
  $login: String!
  $provider: VCSProviderChoices!
  $isActivated: Boolean
  $first: Int
  $after: String
  $offset: Int
  $q: String
) {
  owner(login: $login, provider: $provider) {
    id
    repositories(
      isActivated: $isActivated
      first: $first
      after: $after
      offset: $offset
      name_Icontains: $q
    ) {
      totalCount
      edges {
        node {
          id
          name
          ownerLogin
        }
      }
    }
  }
}
