import { TransformerRun } from "~/types/types";
import { TransformerRunDetailModuleState } from "~/store/transformerRun/detail"

/**
 * Mock for transformer run detail.
 */
export const TRANSFORMER_RUN_DETAIL: TransformerRun = <TransformerRun>{
  "errors": "[]",
  "pullRequestStatus": "PNC",
  "status": "PASS",
  "tools": [
    {
      "name": "Black",
      "shortcode": "black",
      "logo_path": "https://s3.us-east-1.amazonaws.com/local-asgard-static/transformer_logos/black.svg",
      "description": "The uncompromising Python code formatter"
    }
  ],
  "changedFilesCount": 8,
  "commitStatus": null,
  "id": "VHJhbnNmb3JtZXJSdW46NDQ5",
  "changeset": {
    "core/models/owner.py": [
      {
        "id": 11041,
        "action": "modified",
        "before_html": "<div class=\"highlight\"><pre><span class=\"ln\">289</span><span class=\"s2\"></span><span class=\"s2\">        type team then add that user as admin team member</span><span class=\"s2\"></span>\n<span class=\"ln\">290</span><span class=\"s2\"></span><span class=\"s2\">        </span><span class=\"s2\">&#34;&#34;&#34;</span>\n<span class=\"ln\">291</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">primary_user</span> <span class=\"o\">=</span> <span class=\"n\">user</span>\n<span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">292</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">save</span><span class=\"p\">(</span><span class=\"n\">update_fields</span><span class=\"o\">=</span><span class=\"p\">[</span><span class=\"sa\"></span><span class=\"s1\">&#39;</span><span class=\"s1\">primary_user</span><span class=\"s1\">&#39;</span><span class=\"p\">]</span><span class=\"p\">)</span></span><span class=\"ln\">293</span>        <span class=\"n\">logger</span><span class=\"o\">.</span><span class=\"n\">info</span><span class=\"p\">(</span>\n<span class=\"ln\">294</span>            <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No primary user set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as primary user</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span>\n<span class=\"ln\">295</span>            <span class=\"bp\">self</span><span class=\"p\">,</span></pre></span>",
        "after_html": "<div class=\"highlight\"><pre><span class=\"ln\">289</span><span class=\"s2\"></span><span class=\"s2\">        type team then add that user as admin team member</span><span class=\"s2\"></span>\n<span class=\"ln\">290</span><span class=\"s2\"></span><span class=\"s2\">        </span><span class=\"s2\">&#34;&#34;&#34;</span>\n<span class=\"ln\">291</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">primary_user</span> <span class=\"o\">=</span> <span class=\"n\">user</span>\n<span class=\"hlg\" data-code-marker=\"+\"><span class=\"ln\">292</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">save</span><span class=\"p\">(</span><span class=\"n\">update_fields</span><span class=\"o\">=</span><span class=\"p\">[</span><span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">primary_user</span><span class=\"s2\">&#34;</span><span class=\"p\">]</span><span class=\"p\">)</span></span><span class=\"ln\">293</span>        <span class=\"n\">logger</span><span class=\"o\">.</span><span class=\"n\">info</span><span class=\"p\">(</span>\n<span class=\"ln\">294</span>            <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No primary user set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as primary user</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"bp\">self</span><span class=\"p\">,</span> <span class=\"n\">user</span><span class=\"p\">,</span>\n<span class=\"ln\">295</span>        <span class=\"p\">)</span></pre></span>"
      },
      {
        "id": 11042,
        "action": "modified",
        "before_html": "<div class=\"highlight\"><pre><span class=\"ln\">291</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">primary_user</span> <span class=\"o\">=</span> <span class=\"n\">user</span>\n<span class=\"ln\">292</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">save</span><span class=\"p\">(</span><span class=\"n\">update_fields</span><span class=\"o\">=</span><span class=\"p\">[</span><span class=\"sa\"></span><span class=\"s1\">&#39;</span><span class=\"s1\">primary_user</span><span class=\"s1\">&#39;</span><span class=\"p\">]</span><span class=\"p\">)</span>\n<span class=\"ln\">293</span>        <span class=\"n\">logger</span><span class=\"o\">.</span><span class=\"n\">info</span><span class=\"p\">(</span>\n<span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">294</span>            <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No primary user set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as primary user</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span></span><span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">295</span>            <span class=\"bp\">self</span><span class=\"p\">,</span></span><span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">296</span>            <span class=\"n\">user</span><span class=\"p\">,</span></span><span class=\"ln\">297</span>        <span class=\"p\">)</span>\n<span class=\"ln\">298</span>        <span class=\"k\">if</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">owner_type</span> <span class=\"o\">==</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">TEAM</span><span class=\"p\">:</span>\n<span class=\"ln\">299</span>            <span class=\"n\">TeamMember</span> <span class=\"o\">=</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">team</span><span class=\"o\">.</span><span class=\"n\">members</span><span class=\"o\">.</span><span class=\"n\">through</span></pre></span>",
        "after_html": "<div class=\"highlight\"><pre><span class=\"ln\">291</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">primary_user</span> <span class=\"o\">=</span> <span class=\"n\">user</span>\n<span class=\"ln\">292</span>        <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">save</span><span class=\"p\">(</span><span class=\"n\">update_fields</span><span class=\"o\">=</span><span class=\"p\">[</span><span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">primary_user</span><span class=\"s2\">&#34;</span><span class=\"p\">]</span><span class=\"p\">)</span>\n<span class=\"ln\">293</span>        <span class=\"n\">logger</span><span class=\"o\">.</span><span class=\"n\">info</span><span class=\"p\">(</span>\n<span class=\"hlg\" data-code-marker=\"+\"><span class=\"ln\">294</span>            <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No primary user set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as primary user</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"bp\">self</span><span class=\"p\">,</span> <span class=\"n\">user</span><span class=\"p\">,</span></span>\n\n<span class=\"ln\">295</span>        <span class=\"p\">)</span>\n<span class=\"ln\">296</span>        <span class=\"k\">if</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">owner_type</span> <span class=\"o\">==</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">TEAM</span><span class=\"p\">:</span>\n<span class=\"ln\">297</span>            <span class=\"n\">TeamMember</span> <span class=\"o\">=</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">team</span><span class=\"o\">.</span><span class=\"n\">members</span><span class=\"o\">.</span><span class=\"n\">through</span></pre></span>"
      },
      {
        "id": 11043,
        "action": "modified",
        "before_html": "<div class=\"highlight\"><pre><span class=\"ln\">297</span>        <span class=\"p\">)</span>\n<span class=\"ln\">298</span>        <span class=\"k\">if</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">owner_type</span> <span class=\"o\">==</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">TEAM</span><span class=\"p\">:</span>\n<span class=\"ln\">299</span>            <span class=\"n\">TeamMember</span> <span class=\"o\">=</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">team</span><span class=\"o\">.</span><span class=\"n\">members</span><span class=\"o\">.</span><span class=\"n\">through</span>\n<span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">300</span>            <span class=\"n\">TeamMember</span><span class=\"o\">.</span><span class=\"n\">objects</span><span class=\"o\">.</span><span class=\"n\">create</span><span class=\"p\">(</span></span><span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">301</span>                <span class=\"n\">team</span><span class=\"o\">=</span><span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">team</span><span class=\"p\">,</span> <span class=\"n\">user</span><span class=\"o\">=</span><span class=\"n\">user</span><span class=\"p\">,</span> <span class=\"n\">role</span><span class=\"o\">=</span><span class=\"n\">TeamMember</span><span class=\"o\">.</span><span class=\"n\">ADMIN</span></span><span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">302</span>            <span class=\"p\">)</span></span><span class=\"ln\">303</span>            <span class=\"n\">logger</span><span class=\"o\">.</span><span class=\"n\">info</span><span class=\"p\">(</span>\n<span class=\"ln\">304</span>                <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No team member set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as admin</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"bp\">self</span><span class=\"p\">,</span> <span class=\"n\">user</span>\n<span class=\"ln\">305</span>            <span class=\"p\">)</span></pre></span>",
        "after_html": "<div class=\"highlight\"><pre><span class=\"ln\">295</span>        <span class=\"p\">)</span>\n<span class=\"ln\">296</span>        <span class=\"k\">if</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">owner_type</span> <span class=\"o\">==</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">TEAM</span><span class=\"p\">:</span>\n<span class=\"ln\">297</span>            <span class=\"n\">TeamMember</span> <span class=\"o\">=</span> <span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">team</span><span class=\"o\">.</span><span class=\"n\">members</span><span class=\"o\">.</span><span class=\"n\">through</span>\n<span class=\"hlg\" data-code-marker=\"+\"><span class=\"ln\">298</span>            <span class=\"n\">TeamMember</span><span class=\"o\">.</span><span class=\"n\">objects</span><span class=\"o\">.</span><span class=\"n\">create</span><span class=\"p\">(</span><span class=\"n\">team</span><span class=\"o\">=</span><span class=\"bp\">self</span><span class=\"o\">.</span><span class=\"n\">team</span><span class=\"p\">,</span> <span class=\"n\">user</span><span class=\"o\">=</span><span class=\"n\">user</span><span class=\"p\">,</span> <span class=\"n\">role</span><span class=\"o\">=</span><span class=\"n\">TeamMember</span><span class=\"o\">.</span><span class=\"n\">ADMIN</span><span class=\"p\">)</span></span>\n\n<span class=\"ln\">299</span>            <span class=\"n\">logger</span><span class=\"o\">.</span><span class=\"n\">info</span><span class=\"p\">(</span>\n<span class=\"ln\">300</span>                <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No team member set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as admin</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"bp\">self</span><span class=\"p\">,</span> <span class=\"n\">user</span>\n<span class=\"ln\">301</span>            <span class=\"p\">)</span></pre></span>"
      },
      {
        "id": 11044,
        "action": "modified",
        "before_html": "<div class=\"highlight\"><pre><span class=\"ln\">304</span>                <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No team member set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as admin</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"bp\">self</span><span class=\"p\">,</span> <span class=\"n\">user</span>\n<span class=\"ln\">305</span>            <span class=\"p\">)</span>\n<span class=\"ln\">306</span>\n<span class=\"hlr\" data-code-marker=\"-\"><span class=\"ln\">307</span></span><span class=\"ln\">308</span>    <span class=\"k\">class</span> <span class=\"nc\">Meta</span><span class=\"p\">:</span>\n<span class=\"ln\">309</span>        <span class=\"n\">unique_together</span> <span class=\"o\">=</span> <span class=\"p\">(</span><span class=\"p\">(</span><span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">login</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">vcs_provider</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">alive</span><span class=\"s2\">&#34;</span><span class=\"p\">)</span><span class=\"p\">,</span><span class=\"p\">)</span>\n<span class=\"ln\">310</span>        <span class=\"n\">permissions</span> <span class=\"o\">=</span> <span class=\"p\">[</span></pre></span>",
        "after_html": "<div class=\"highlight\"><pre><span class=\"ln\">300</span>                <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">No team member set for owner </span><span class=\"si\">%s</span><span class=\"s2\">, setting </span><span class=\"si\">%s</span><span class=\"s2\"> as admin</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"bp\">self</span><span class=\"p\">,</span> <span class=\"n\">user</span>\n<span class=\"ln\">301</span>            <span class=\"p\">)</span>\n<span class=\"ln\">302</span>\n\n<span class=\"ln\">303</span>    <span class=\"k\">class</span> <span class=\"nc\">Meta</span><span class=\"p\">:</span>\n<span class=\"ln\">304</span>        <span class=\"n\">unique_together</span> <span class=\"o\">=</span> <span class=\"p\">(</span><span class=\"p\">(</span><span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">login</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">vcs_provider</span><span class=\"s2\">&#34;</span><span class=\"p\">,</span> <span class=\"sa\"></span><span class=\"s2\">&#34;</span><span class=\"s2\">alive</span><span class=\"s2\">&#34;</span><span class=\"p\">)</span><span class=\"p\">,</span><span class=\"p\">)</span>\n<span class=\"ln\">305</span>        <span class=\"n\">permissions</span> <span class=\"o\">=</span> <span class=\"p\">[</span></pre></span>"
      }
    ]
  },
  "vcsPrUrl": "https://github.com/deepsourcelabs/asgard/pull/1888",
  "vcsCommitUrl": null
}

/**
 * Mock -- Transformer run detail factory
 * @see TRANSFORMER_RUN_DETAIL
 */
export const mockTransformerRunDetail = (): TransformerRun => TRANSFORMER_RUN_DETAIL;

/**
 * Mock factory
 */
export const mockTransformerRunDetailState = (): TransformerRunDetailModuleState => ({
  loading: false as boolean,
  error: {},
  transformerRun: mockTransformerRunDetail()
});