package run

import (
	"encoding/json"
	"fmt"

	"github.com/deepsourcelabs/cli/analysis/processor"
	"github.com/deepsourcelabs/cli/types"
)

// processAnalyzerReport processes the analysis report generated by the Analyzer
func (a *AnalyzerDryRun) processAnalyzerReport(reportBytes []byte) (types.AnalysisResult, error) {
	report := types.AnalyzerReport{}

	// Convert the analysis result from the LSP based format to the default DeepSource format
	processor := processor.ProcessAnalysisResults{
		CodePath:   a.SourcePath,
		Processors: a.Processors,
	}

	if err := json.Unmarshal(reportBytes, &report); err != nil {
		fmt.Println(err)
		return types.AnalysisResult{}, err
	}

	processor.Report = report
	processor.ProcessAnalysisResult()
	return processor.AnalysisResult, nil
}
