package run

import (
	"encoding/json"
	"fmt"

	"github.com/deepsourcelabs/cli/analysis/processor"
	"github.com/deepsourcelabs/cli/analysis/processor/processors"
	"github.com/deepsourcelabs/cli/types"
)

// processAnalyzerReport processes the analysis report generated by the Analyzer
func (a *AnalyzerDryRun) processAnalyzerReport(reportBytes []byte) (types.AnalysisResult, error) {
	report := types.AnalyzerReport{}
	skipCQProcessor := processors.ProcSkipCQ{}
	sourceCodeHighlightingProcessor := processors.ProcSourceCodeLoad{}

	// Initializing the processors using the IProcessor interface provided by the `processor` package
	var skip_cq, source_code_load processor.IProcessor
	skip_cq = skipCQProcessor
	source_code_load = sourceCodeHighlightingProcessor

	processor := processor.ConfigureProcessors{
		CodePath:   a.SourcePath,
		Processors: []processor.IProcessor{skip_cq, source_code_load},
	}

	// Generate the silencers regexMap.
	processors.GenerateSilencersRegexMap()

	if err := json.Unmarshal(reportBytes, &report); err != nil {
		fmt.Println(err)
		return types.AnalysisResult{}, err
	}

	processor.Report = report
	analysisResult := processor.ProcessAnalyzerReport()
	return analysisResult, nil
}
