query ($q: String, $first: Int, $offset: Int) {
  enterprise {
    isScimEnabled
    groups(q: $q, first: $first, offset: $offset) {
      totalCount
      edges {
        node {
          id
          name
          createdAt
          scimEnabled
          members {
            totalCount
          }
          teams {
            totalCount
          }
        }
      }
    }
  }
}
