query($id: ID!, $q: String, $first: Int, $offset: Int) {
  enterprise {
    group(id: $id) {
      id
      name
      createdAt
      membersCount: members {
        totalCount
      }
      members(q: $q, first: $first, offset: $offset) {
        totalCount
        edges {
          node {
            id
            avatar
            fullName
            email
          }
        }
      }
      teamsCount: groupTeams {
        totalCount
      }
    }
  }
}
