query enterpriseUsers($q: String, $first: Int, $offset: Int) {
  enterprise {
    users(q: $q, first: $first, offset: $offset) {
      totalCount
      edges {
        node {
          id
          avatar
          fullName
          email
          isActive
          isSuperuser
          scimEnabled
          teams {
            edges {
              node {
                name
              }
            }
          }
          groupsCount: scimGroups {
            totalCount
          }
        }
      }
    }
  }
}
