query ($id: ID!, $q: String, $first: Int, $offset: Int) {
  enterprise {
    user(id: $id) {
      id
      fullName
      avatar
      email
      dateJoined
      isActive
      isSuperuser
      scimEnabled
      groupsCount: scimGroups {
        totalCount
      }
      scimGroups(q: $q, first: $first, offset: $offset) {
        totalCount
        edges {
          node {
            id
            name
            scimEnabled
            members {
              totalCount
            }
            teams {
              totalCount
            }
          }
        }
      }
    }
  }
}
