query ownerAutofixedIssueTrend($login: String!, $provider: VCSProviderChoices!, $lastDays: Int!) {
  owner(login: $login, provider: $provider) {
    id
    autofixedIssueTrend(lastDays: $lastDays)
  }
}
