query billingFat($login: String!, $provider: VCSProviderChoices!) {
  owner(login: $login, provider: $provider) {
    id
    login
    billingEmail
    billingAddress
    vcsInstallationId
    hasPremiumPlan
    login
    billingInfo {
      planSlug
      status
      upgradePlans
      downgradePlans
      seatsTotal
      seatsUsed
      lastBillAmount
      upcomingBillAmount
      lastPaymentDate
      upcomingPaymentDate
      lastInvoiceUrl
      cancelAtPeriodEnd
      upcomingCancellationDate
      outstandingCredits
      billingBackend
      synced
      pendingUpdate
      clientSecret
      couponApplied {
        code
        description
      }
      activeCard {
        brand
        endingIn
        expYear
        expMonth
      }
      invoices {
        invoiceId
        date
        amount
        url
      }
    }
  }
}
