query($login: String!, $provider: VCSProviderChoices!) {
  owner(login: $login, provider: $provider) {
    id
    isTeam
    vcsInstallationId
    hasSubscribedToPlan
    autofixInstallationUrl
    isAutofixEnabled
    isAutoonboardAllowed
    hasPremiumPlan
    team {
      id
    }
    primaryUser {
      id
      email
      fullName
    }
  }
}
