query issueTrend($login: String!, $provider: VCSProviderChoices!, $lastDays: Int!) {
  owner(login: $login, provider: $provider) {
    id
    issueTrend(lastDays: $lastDays)
    resolvedIssueTrend(lastDays: $lastDays)
  }
}
