query VCSData($login: String!, $provider: VCSProviderChoices!) {
  owner(login: $login, provider: $provider) {
    id
    vcsInstallationId
    autofixInstallationUrl
    isAutofixEnabled
    team {
      id
    }
  }
}
