query ($lastDays: Int!, $trendType: TrendType!) {
  enterprise {
    license {
      seatsTotal
      seatsUsed
      licenseExpiry
      seatUsageTrend(lastDays: $lastDays, trendType: $trendType)
    }
  }
}
