query discoverRepositories($preferredTechnologies: [ID], $q: String, $first: Int, $after: String) {
  discoverRepositories(
    preferredTechnologies: $preferredTechnologies
    q: $q
    first: $first
    after: $after
  ) {
    totalCount
    edges {
      node {
        id
        modifiedAt
        name
        description
        vcsProvider
        hasHacktoberfestEnabled
        recommendedIssueCount
        isWatched
        owner {
          login
        }
        primaryAnalyzer {
          id
          name
          shortcode
          analyzerLogo
        }
      }
    }
  }
}
