query($preferredTechnologies: [ID], $q: String) {
  discoverRepositories(preferredTechnologies: $preferredTechnologies, q: $q) {
    totalCount
    edges {
      node {
        id
        modifiedAt
        name
        description
        vcsProvider
        recommendedIssueCount
        isWatched
        owner {
          login
        }
        primaryAnalyzer {
          id
          name
          shortcode
          analyzerLogo
        }
      }
    }
  }
}
