query($q: String) {
  discoverRepositories(q: $q) {
    totalCount
    edges {
      node {
        id
        modifiedAt
        name
        description
        vcsProvider
        fullName
        recommendedIssueCount
        isWatched
        primaryAnalyzer {
          id
          name
          shortcode
          analyzerLogo
        }
      }
    }
  }
}
