query {
  editorsPickRepository {
    id
    name
    description
    fullName
    recommendedIssueCount
    isWatched
    primaryAnalyzer {
      id
      name
      shortcode
      analyzerLogo
    }
  }
}
