query editorsPickRepository {
  editorsPickRepository {
    id
    name
    description
    recommendedIssueCount
    hasHacktoberfestEnabled
    isWatched
    owner {
      login
    }
    primaryAnalyzer {
      id
      name
      shortcode
      analyzerLogo
    }
  }
}
