query preferredTechnologies {
  viewer {
    id
    preferredTechnologies {
      totalCount
      edges {
        node {
          id
          shortcode
          analyzerLogo
        }
      }
    }
  }
}
