query {
  trendingRepositories {
    totalCount
    edges {
      node {
        id
        name
        description
        vcsProvider
        recommendedIssueCount
        hasHacktoberfestEnabled
        isWatched
        owner {
          login
        }
        primaryAnalyzer {
          id
          name
          shortcode
          analyzerLogo
        }
      }
    }
  }
}
