query {
  viewer {
    id
    preference {
      watchedRepositories {
        totalCount
        edges {
          node {
            id
            modifiedAt
            name
            description
            vcsProvider
            recommendedIssueCount
            hasHacktoberfestEnabled
            isWatched
            owner {
              login
            }
            primaryAnalyzer {
              id
              name
              shortcode
              analyzerLogo
            }
          }
        }
      }
    }
  }
}
