query ($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, owner: $owner, name: $name) {
    id
    showInDiscover
    analyzeChangesetOnly
    defaultBranchName
    isSubmoduleEnabled
    config
    isActivated
    isPrivate
  }
}
