query($provider: VCSProviderChoices!, $owner: String!, $name: String!) {
  repository(provider: $provider, owner: $owner, name: $name) {
    id
    name
    dsn
    hasTestCoverage
    issueTypeSettings {
      name
      slug
      description
      isIgnoredInCheckStatus
      isIgnoredToDisplay
    }
    issuePrioritySettings {
      slug
      weight
      verboseName
      isIgnoredInCheckStatus
      isIgnoredToDisplay
    }
  }
}
