query(
  $level: IssuePriorityLevel!
  $objectId: ID!
  $isIssuePrioritySet: Boolean
  $first: Int
  $after: String
  $sort: String
  $q: String
  $offset: Int
  $analyzerShortcode: String
) {
  issuesWithPriority(
    level: $level
    objectId: $objectId
    isIssuePrioritySet: $isIssuePrioritySet
    first: $first
    after: $after
    sort: $sort
    q: $q
    offset: $offset
    analyzerShortcode: $analyzerShortcode
  ) {
    totalCount
    edges {
      node {
        id
        issueType
        title
        shortcode
        description
        analyzer {
          name
          logo
          analyzerLogo
          shortcode
        }
        issuePriority(level: $level, objectId: $objectId) {
          repositoryIssuePriority {
            slug
            weight
            verboseName
          }
          ownerIssuePriority {
            slug
            weight
            verboseName
          }
        }
      }
    }
  }
}
