query singleIssueWithPriority($shortcode: String!, $objectId: ID!, $level: IssuePriorityLevel!) {
  issue(shortcode: $shortcode) {
    id
    issuePriority(level: $level, objectId: $objectId) {
      cascadingIssuePriority {
        id
        slug
        verboseName
        weight
      }
      source
    }
  }
}
