query ($q: String) {
  transformers(q: $q) {
    edges {
      node {
        name
        owner
        descriptionRendered
        updatedOn
        language
        version
        shortcode
        publishedOn
        logo
        createdAt
        analyzer {
          analyzerLogo
        }
      }
    }
  }
}
