query issueTypeSettings($login: String!, $provider: VCSProviderChoices!) {
  owner(login: $login, provider: $provider) {
    id
    ownerSetting {
      id
      issueTypeSettings {
        slug
        name
        isIgnoredInCheckStatus
        isIgnoredToDisplay
        description
      }
    }
  }
}
