{
  viewer {
    id
    fullName
    firstName
    lastName
    email
    avatar
    lastLogin
    isActive
    isStaff
    primaryOwner {
      id
      login
      vcsProvider
      billingEmail
    }
  }
}
