query($runId: String!) {
  autofixRun(runId: $runId) {
    id
    errors
    finishedIn
    issuesAffected
    committedToBranchStatus
    resolvedIssuesCount
    pullRequestStatus
    status
    id
    changeset
    vcsPrUrl
  }
}
