apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: bifrost-master-builds
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            imagePullPolicy: 'IfNotPresent'
            env:
              - name: HOME
                value: /tekton/home
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /secret/kaniko.json
              - name: GOOGLE_ANALYTICS_ID
                value: UA-XXXXXXXX-X
              - name: DISABLE_SENTRY
                value: 'true'
              - name: TRIVY_EXIT_CODE
                value: '0'
              - name: TRIVY_CACHE_DIR
                value: /trivycache
              - name: TRIVY_SEVERITY
                value: HIGH,CRITICAL,MEDIUM,LOW
            envFrom:
              - secretRef:
                  name: jx-boot-job-env-vars
                  optional: true
              - secretRef:
                  name: zeal-secret
              - secretRef:
                  name: stripe-publishable
              - secretRef:
                  name: defectdojo-api
            name: ''
          steps:
            - image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.27.0
              name: git-clone
              resources: {}
              script: |
                #!/bin/sh
                export SUBDIR="source"
                echo "git cloning url: $REPO_URL version $PULL_BASE_REF@$PULL_BASE_SHA to dir: $SUBDIR"
                git config --global user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
                git config --global user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
                git config --global credential.helper store
                git clone $REPO_URL $SUBDIR
                cd $SUBDIR
                git reset --hard $PULL_BASE_SHA
                echo "checked out revision: $PULL_BASE_REF@$PULL_BASE_SHA to dir: $SUBDIR"
              workingDir: /workspace
            - image: ghcr.io/jenkins-x/jx-boot:3.2.157
              name: jx-variables
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx gitops variables
              workingDir: /workspace/source
            - name: warm-cache
              image: gcr.io/kaniko-project/warmer:latest
              args:
                - --cache-dir=/kanikocache
                - --image=node:14.19-alpine
                - --image=frolvlad/alpine-glibc:alpine-3.15_glibc-2.34
              workingDir: /workspace/source
            - image: gcr.io/kaniko-project/executor:v1.6.0-debug
              name: container-build
              resources:
                requests:
                  memory: 6Gi
                  cpu: 5
              script: |
                #!/busybox/sh
                source .jx/variables.sh
                /kaniko/executor --cache-repo=us.gcr.io/deepsource-dev/$REPO_NAME --tarPath=/workspace/source/$REPO_NAME.tar --build-arg=GOOGLE_ANALYTICS_ID=UA-XXXXXXXX-X --build-arg=DISABLE_SENTRY=true --build-arg=ZEAL_SECRET=$ZEAL_SECRET --build-arg=STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY --context=/workspace/source --dockerfile=Dockerfile --destination=us.gcr.io/deepsource-dev/$REPO_NAME:master --cache=true --snapshotMode=redo --cache-dir=/kanikocache
              workingDir: /workspace/source
            - name: scan-image
              image: aquasec/trivy:0.36.1
              envFrom:
                - secretRef:
                    name: trivy-db-secret
              args:
                - image
                - -f
                - json
                - -o
                - bifrost-results.json
                - --input
                - bifrost.tar
              workingDir: /workspace/source
            - name: create-defectdojo-engagement
              image: us.gcr.io/deepsource-dev/crane:alpine
              script: |
                #!/bin/sh
                source .jx/variables.sh && \
                export DATE=`date +%Y-%m-%d` && \
                apk add curl && apk add git && \
                apk add jq && \
                curl -X 'GET' 'http://defectdojo.deepsource.icu/api/v2/engagements/?product=5&name=master' \
                -H 'accept: application/json' \
                -H 'Authorization: Token '"$DEFECTDOJO_API"'' > engagement_result.txt
                RESULT_LEN=$(cat engagement_result.txt | jq '.["results"] | length')
                rm engagement_result.txt && \
                if [[ $RESULT_LEN == 0 ]]; then
                  curl -X 'POST' \
                  'http://defectdojo.deepsource.icu/api/v2/engagements/' \
                  -H 'accept: application/json' -H 'Content-Type: multipart/form-data' \
                  -H 'Authorization: Token '"$DEFECTDOJO_API"'' \
                  -F 'name=master' \
                  -F 'minimum_severity=Info' \
                  -F 'branch_tag=master' \
                  -F 'product=5' \
                  -F 'target_start='"$DATE"'' \
                  -F 'target_end='"$DATE"'' \
                  -F 'status=In Progress' 
                else
                  exit 0
                fi
              workingDir: /workspace/source
            - name: push-defectdojo
              image: us.gcr.io/deepsource-dev/crane:alpine
              script: |
                #!/bin/sh
                source .jx/variables.sh && \
                export DATE=`date +%Y-%m-%d` && \
                apk add curl && apk add jq && \
                curl -X 'GET' \
                'http://defectdojo.deepsource.icu/api/v2/tests/?title='"$REPO_NAME"'-master' \
                -H 'accept: application/json' \
                -H 'Authorization: Token '"$DEFECTDOJO_API"'' > test_result.txt && \
                RESULT_LEN=$(cat test_result.txt | jq '.["results"] | length') && \
                rm test_result.txt && \
                if [[ $RESULT_LEN == 0 ]]; then
                  curl -X 'POST' \
                  'http://defectdojo.deepsource.icu/api/v2/import-scan/' \
                  -H 'accept: application/json' \
                  -H 'Content-Type: multipart/form-data' \
                  -H 'Authorization: Token '"$DEFECTDOJO_API"'' \
                  -F 'scan_date='"$DATE"'' \
                  -F 'minimum_severity=Info' \
                  -F 'active=true' \
                  -F 'verified=true' \
                  -F 'test_title='"$REPO_NAME"'-master' \
                  -F 'scan_type=Trivy Scan' \
                  -F 'file=@bifrost-results.json;type=application/json' \
                  -F 'product_type_name=deepsourcelabs' \
                  -F 'product_name='"$REPO_NAME"'' \
                  -F 'engagement_name=master' \
                  -F 'tags=vuln_scan,trivy' \
                  -F 'close_old_findings=true' \
                  -F 'close_old_findings_product_scope=false' \
                  -F 'push_to_jira=false' \
                  -F 'build_id=master' \
                  -F 'commit_hash='"$PR_BASE_SHA"'' \
                  -F 'create_finding_groups_for_all_findings=true' \
                  -F 'deduplication_on_engagement=true'
                else
                  curl -X 'POST' \
                  'http://defectdojo.deepsource.icu/api/v2/reimport-scan/' \
                  -H 'accept: application/json' \
                  -H 'Content-Type: multipart/form-data' \
                  -H 'Authorization: Token '"$DEFECTDOJO_API"'' \
                  -F 'minimum_severity=Info' \
                  -F 'active=true' \
                  -F 'verified=true' \
                  -F 'do_not_reactivate=true' \
                  -F 'scan_type=Trivy Scan' \
                  -F 'file=@bifrost-results.json;type=application/json' \
                  -F 'product_name='"$REPO_NAME"'' \
                  -F 'engagement_name=master' \
                  -F 'test_title='"$REPO_NAME"'-master' \
                  -F 'deduplication_on_engagement=true' \
                  -F 'push_to_jira=false' \
                  -F 'close_old_findings=true' \
                  -F 'close_old_findings_product_scope=false' \
                  -F 'create_finding_groups_for_all_findings=true'
                fi
              workingDir: /workspace/source
          workspaces:
            - name: kanikocache
              mountPath: /kanikocache
            - name: kaniko
              mountPath: /secret
            - name: trivycache
              mountPath: /trivycache
            - name: defectdojo-api
        workspaces:
          - name: kanikocache
            workspace: bifrost-cache
            subPath: kanikocache
          - name: kaniko
            workspace: kaniko
          - name: trivycache
            workspace: bifrost-cache
            subPath: trivycache
          - name: defectdojo-api
            workspace: defectdojo-api
    workspaces:
      - name: bifrost-cache
      - name: kaniko
      - name: defectdojo-api
  workspaces:
    - name: bifrost-cache
      persistentVolumeClaim:
        claimName: bifrost-cache
    - name: kaniko
      secret:
        secretName: kaniko
    - name: zeal
      secret:
        secretName: zeal-secret
    - name: stripe
      secret:
        secretName: stripe-publishable
    - name: secret
      secret:
        secretName: trivy-db-secret
    - name: defectdojo-api
      secret:
        secretName: defectdojo-api
  podTemplate:
    nodeSelector:
      scheduledBy: jx
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
