apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: bifrost-pr-deploy
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          imagePullPolicy: "IfNotPresent"
          env:
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.2.157
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
            jx gitops pr variables
          workingDir: /workspace
        - image: roffe/kubectl:v1.13.2
          name: deploy-bifrost
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            kubectl set image deployment/bifrost bifrost=us.gcr.io/deepsource-dev/bifrost:$BRANCH_NAME -n default
          workingDir: /workspace
  podTemplate: 
    nodeSelector:
      scheduledBy: jx
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
