apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: bifrost-pr-test
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            imagePullPolicy: 'IfNotPresent'
            env:
              - name: HOME
                value: /tekton/home
              - name: YARN_CACHE_FOLDER
                value: /yarncache
            envFrom:
              - secretRef:
                  name: jx-boot-job-env-vars
                  optional: true
              - secretRef:
                  name: zeal-secret
              - secretRef:
                  name: bifrost-dsn
          steps:
            - image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.19.0
              name: git-clone
              resources: {}
              script: |
                #!/bin/sh
                export SUBDIR="source"
                echo "git cloning url: $REPO_URL version $PULL_PULL_REF:$(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER@$PULL_PULL_SHA to dir: $SUBDIR"
                git config --global user.name ${GIT_AUTHOR_NAME}
                git config --global user.email ${GIT_AUTHOR_EMAIL}
                git config --global credential.helper store
                git clone $REPO_URL $SUBDIR
                cd $SUBDIR
                git fetch origin $PULL_PULL_REF:$(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER
                git checkout $(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER
                git reset --hard $PULL_PULL_SHA
                echo "checked out revision: $PULL_PULL_REF:$(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER@$PULL_PULL_SHA to dir: $SUBDIR"
              workingDir: /workspace
            - image: node:14.18-alpine
              name: run-tests
              resources:
                requests:
                  cpu: 5
                  memory: 6Gi
              script: |
                #!/bin/sh
                apk update && \
                apk add --no-cache curl git && \
                yarn install && \
                yarn test --cache --coverage=true --coverageReporters=cobertura && \
                curl https://deepsource.io/cli | sh && \
                ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
              workingDir: /workspace/source
          workspaces:
            - name: yarncache
              mountPath: /yarncache
            - name: jestcache
              mountPath: /jestcache
        workspaces:
          - name: yarncache
            workspace: bifrost-cache
            subPath: yarncache
          - name: jestcache
            workspace: bifrost-cache
            subPath: jestcache
    workspaces:
      - name: bifrost-cache
  workspaces:
    - name: bifrost-cache
      persistentVolumeClaim:
        claimName: bifrost-cache
    - name: zeal
      secret:
        secretName: zeal-secret
    - name: dsn
      secret:
        secretName: bifrost-dsn
  podTemplate:
    nodeSelector:
      scheduledBy: jx
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
