apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
name: bifrost-trigger-config
spec:
  presubmits:
    - name: bifrost-deploy
      context: 'Bifrost-Run-Deploy'
      always_run: false
      optional: true
      source: 'pullrequest-deploy.yaml'
    - name: bifrost-deploy-enterprise
      context: 'Bifrost-Run-Deploy-Enterprise'
      always_run: false
      optional: true
      source: 'pullrequest-deploy-enterprise.yaml'
