query teamInvites(
  $login: String!
  $provider: VCSProviderChoices!
  $limit: Int
  $after: String
  $q: String
) {
  team(login: $login, provider: $provider) {
    id
    invites(first: $limit, after: $after, q: $q) {
      totalCount
      edges {
        node {
          email
          createdAt
          role
        }
      }
    }
  }
}
