query fetchTeamPermissions($login: String!, $provider: VCSProviderChoices!) {
  team(login: $login, provider: $provider) {
    id
    login
    syncPermissionsWithVcs
    basePermissionSet {
      team {
        id
      }
      id
      defaultRepositoryPermission
      canMembersIgnoreIssues
      canContributorsIgnoreIssues
      canMembersModifyMetricThresholds
      canContributorsModifyMetricThresholds
      canMembersIgnoreFailingMetrics
      canContributorsIgnoreFailingMetrics
    }
  }
}
