name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  release-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          workdir: ./cmd/deepsource
          args: release --rm-dist --config ../../goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.DS_BOT_PAT }}
          DEEPSOURCE_CLI_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
