name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Setup environment variables
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' >> .release-env
          echo 'HOMEBREW_TOKEN=${{secrets.DS_BOT_PAT}}' >> .release-env
          echo 'DEEPSOURCE_CLI_SENTRY_DSN=${{secrets.SENTRY_DSN}}' >> .release-env

      - name: Publish Release
        run: make release
