name: goreleaser

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v4
      #   with:
      #     distribution: goreleaser
      #     version: latest
      #     workdir: ./cmd/deepsource
      #     args: release --clean --skip-publish --skip-validate --config ../../goreleaser.yaml
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     HOMEBREW_TOKEN: ${{ secrets.DS_BOT_PAT }}
      #     DEEPSOURCE_CLI_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: setup env
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
          echo 'HOMEBREW_TOKEN=${{secrets.DS_BOT_PAT}}' > .release-env
          echo 'DEEPSOURCE_CLI_SENTRY_DSN=${{secrets.SENTRY_DSN}}' > .release-env
      - name: release publish
        run: make release-dry-run
